# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-18 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engagementApp', '0004_auto_20181206_1404'),
        ('favourites', '0006_auto_20181214_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='engagementApp.Articles'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='display_name',
            field=models.TextField(default='john_doe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(),
        ),
    ]
